version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /percorso-be
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /percorso-fe
    schedule:
      interval: weekly